[platformio]
default_envs = esp32-s3-devkitc-1

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.flash_size = 16MB
board_build.psram_type = opi
build_flags = 
    -D BOARD_HAS_PSRAM
    -D CORE_DEBUG_LEVEL=3
    -D BMS_HARDWARE_TARGET
    -I include
monitor_speed = 115200

[env:native]
platform = native
test_framework = unity
build_flags = 
    -D UNIT_TESTING
    -D BMS_NATIVE_SIMULATION
    -I include
    -std=c++17
