[platformio]
default_envs = esp32-s3-devkitc-1

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_flags = 
    -D BMS_HARDWARE_TARGET
    -D CORE_DEBUG_LEVEL=3
    -I include
monitor_speed = 115200

[env:native]
platform = native
test_framework = unity
test_filter = unit
test_ignore = mocks, helpers, integration, hardware
build_flags = 
    -D UNIT_TESTING
    -D BMS_NATIVE_SIMULATION
    -I include
    -Itest/mocks
    -Itest/helpers
    -std=c++17
